language: dart
sudo: false
dart:
  - dev
install:
  - gem install coveralls-lcov
before_script:
  - ./ci/setup.sh
script:
  - ./ci/ci.sh
after_success:
  - (coveralls-lcov coverage/lcov.info)
cache:
  directories:
    - $HOME/.pub-cache
